refactor curl: rename Status to HttpStatus to avoid name conflict
When moving the component metadata to core, the following error was raised:
MAVSDK/src/mavsdk/plugins/camera/camera.cpp:18:7: error: conflicting declaration ‘using mavsdk::Status = struct mavsdk::Camera::Status’
   18 | using Status = Camera::Status;
      |       ^~~~~~
In file included from MAVSDK/src/mavsdk/core/curl_wrapper.h:6,
                 from MAVSDK/src/mavsdk/core/http_loader.h:9,
                 from MAVSDK/src/mavsdk/core/mavlink_component_metadata.h:5,
                 from MAVSDK/src/mavsdk/core/system_impl.h:5,
                 from MAVSDK/src/mavsdk/core/plugin_impl_base.h:2,
                 from MAVSDK/src/mavsdk/plugins/camera/camera_impl.h:8,
                 from MAVSDK/src/mavsdk/plugins/camera/camera.cpp:7: